select_picture_mode:
  name: Select Picture Mode
  description: Send to samsung TV the command to change picture mode.
  fields:
    entity_id:
      name: Entity Name
      description: Name of the target entity
      required: true
      example: "media_player.tv"
      selector:
        entity:
          integration: samsungtv_smart
    picture_mode:
      name: Picture Mode
      description: Name of the picture mode to switch to. Possible options
        can be found in the picture_mode_list state attribute.
      required: true
      example: "Standard"
      selector:
        text:

set_art_mode:
  name: Set Art Mode
  description: Send to samsung TV the command to set art mode.
  fields:
    entity_id:
      name: Entity Name
      description: Name of the target entity
      required: true
      example: "media_player.tv"
      selector:
        entity:
          integration: samsungtv_smart

select_artwork:
  name: Select Artwork
  description: Display a specific artwork on The Frame TV.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of artwork to display (e.g., 'SAM-F0206')
      required: true
      example: "SAM-F0206"
      selector:
        text:
    show:
      name: Show Immediately
      description: Whether to display artwork immediately
      default: true
      selector:
        boolean:

upload_artwork:
  name: Upload Artwork
  description: Upload a custom image to The Frame TV.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    file_path:
      name: File Path
      description: Path to image file (PNG or JPEG)
      required: true
      example: "/config/www/my_art.png"
      selector:
        text:
    file_type:
      name: File Type
      description: Image format
      default: "PNG"
      selector:
        select:
          options:
            - "PNG"
            - "JPEG"
    matte:
      name: Matte Color
      description: Optional matte color (e.g., 'modern_apricot')
      example: "modern_apricot"
      selector:
        text:

delete_artwork:
  name: Delete Artwork
  description: Remove uploaded artwork from The Frame TV.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of uploaded artwork to delete (e.g., 'MY-F0020')
      required: true
      example: "MY-F0020"
      selector:
        text:

set_photo_filter:
  name: Set Photo Filter
  description: Apply a filter effect to artwork.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of artwork to apply filter to
      required: true
      example: "SAM-F0206"
      selector:
        text:
    filter:
      name: Filter Name
      description: Filter effect to apply (e.g., 'ink', 'watercolor')
      required: true
      example: "ink"
      selector:
        text:

set_art_brightness:
  name: Set Art Mode Brightness
  description: Adjust brightness for Art Mode display.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    brightness:
      name: Brightness
      description: Brightness level (0-10 on most TVs)
      required: true
      example: 5
      selector:
        number:
          min: 0
          max: 10
          mode: slider

set_art_color_temperature:
  name: Set Art Mode Color Temperature
  description: Adjust color temperature for Art Mode display.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    temperature:
      name: Color Temperature
      description: Color temperature value (-5 to 5 on most TVs)
      required: true
      example: 0
      selector:
        number:
          min: -5
          max: 5
          mode: slider

change_artwork_matte:
  name: Change Artwork Matte/Frame
  description: Change the matte or frame style for an artwork.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of artwork to change matte for
      required: true
      example: "MY-F0020"
      selector:
        text:
    matte_id:
      name: Matte Style
      description: Matte/frame style (e.g., 'shadowbox_polar', 'modern_apricot', 'none')
      required: false
      example: "shadowbox_polar"
      selector:
        text:
    portrait_matte_id:
      name: Portrait Matte Style
      description: Matte for portrait orientation (optional)
      required: false
      example: "shadowbox_polar"
      selector:
        text:

set_artwork_favorite:
  name: Set Artwork Favorite
  description: Mark an artwork as favorite or remove from favorites.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of artwork
      required: true
      example: "MY-F0020"
      selector:
        text:
    favorite:
      name: Favorite Status
      description: Mark as favorite
      default: true
      selector:
        boolean:

set_art_slideshow:
  name: Set Art Slideshow
  description: Configure auto-rotation slideshow for Art Mode.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    duration:
      name: Duration
      description: Rotation interval in minutes (0 to disable)
      default: 60
      selector:
        number:
          min: 0
          max: 1440
          unit_of_measurement: "minutes"
    shuffle:
      name: Shuffle
      description: Shuffle artwork order
      default: true
      selector:
        boolean:
    category:
      name: Category
      description: Artwork category (2=My Pictures, 4=Favorites, 8=Store Art)
      default: 2
      selector:
        select:
          options:
            - label: "My Pictures"
              value: "2"
            - label: "Favorites"
              value: "4"
            - label: "Store Art"
              value: "8"

slideshow_next:
  name: Slideshow Next
  description: Advance to next artwork in slideshow queue.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player

slideshow_previous:
  name: Slideshow Previous
  description: Go back to previous artwork in slideshow.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player

slideshow_add_to_queue:
  name: Slideshow Add to Queue
  description: Add artwork to slideshow queue.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of artwork to add to queue
      required: true
      example: "MY-F0020"
      selector:
        text:

slideshow_remove_from_queue:
  name: Slideshow Remove from Queue
  description: Remove artwork from slideshow queue.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of artwork to remove from queue
      required: true
      example: "MY-F0020"
      selector:
        text:

slideshow_set_queue:
  name: Slideshow Set Queue
  description: Replace entire slideshow queue with new list.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_ids:
      name: Artwork IDs
      description: List of artwork IDs (comma-separated or JSON array)
      required: true
      example: "MY-F0020,MY-F0021,SAM-F0206"
      selector:
        text:

slideshow_clear_queue:
  name: Slideshow Clear Queue
  description: Clear all artworks from slideshow queue.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player

slideshow_set_overlay:
  name: Slideshow Set Overlay
  description: Display text overlay immediately, skipping normal queue.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    file_path:
      name: File Path
      description: Path to overlay image file
      required: true
      example: "/config/www/overlay.png"
      selector:
        text:
    duration:
      name: Duration
      description: How long to display overlay in seconds (0 = indefinite)
      default: 30
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: "seconds"
    matte:
      name: Matte
      description: Optional matte style
      example: "none"
      selector:
        text:

slideshow_set_shuffle:
  name: Slideshow Set Shuffle
  description: Enable or disable shuffle mode for slideshow.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    shuffle:
      name: Shuffle
      description: Enable shuffle mode
      default: true
      selector:
        boolean:

slideshow_load_artworks:
  name: Slideshow Load Artworks
  description: Load available artworks from TV for random selection when queue is empty.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    category:
      name: Category
      description: Artwork category (2=My Pictures, 4=Favorites, 8=Store Art)
      default: 2
      selector:
        select:
          options:
            - label: "My Pictures"
              value: "2"
            - label: "Favorites"
              value: "4"
            - label: "Store Art"
              value: "8"

slideshow_set_auto_random:
  name: Slideshow Set Auto Random
  description: Enable or disable automatic random artwork selection when queue is empty.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    enabled:
      name: Enabled
      description: Enable auto-random selection
      default: true
      selector:
        boolean:

overlay_configure:
  name: Configure Overlay
  description: Configure entity sources for dynamic overlay display.
  target:
    entity:
      integration: samsungtv_smart
      domain: switch
  fields:
    calendar_entities:
      name: Calendar Entities
      description: List of calendar entities to display events from
      example: "calendar.personal,calendar.work"
      selector:
        text:
    weather_entity:
      name: Weather Entity
      description: Weather entity to display current conditions
      example: "weather.home"
      selector:
        entity:
          domain: weather
    todo_entities:
      name: Todo Entities
      description: List of todo entities to display items from
      example: "todo.shopping,todo.tasks"
      selector:
        text:
    update_interval:
      name: Update Interval
      description: How often to refresh overlay in seconds
      default: 300
      selector:
        number:
          min: 60
          max: 3600
          unit_of_measurement: "seconds"

overlay_refresh:
  name: Refresh Overlay
  description: Manually trigger an overlay update with current data.
  target:
    entity:
      integration: samsungtv_smart
      domain: switch

overlay_clear:
  name: Clear Overlay
  description: Remove the current overlay and return to underlying artwork.
  target:
    entity:
      integration: samsungtv_smart
      domain: switch

new_artwork:
  name: New Artwork
  description: Download and display a random artwork from a free art museum API.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    matte:
      name: Matte Color
      description: Optional matte color (e.g., 'modern_apricot', 'none')
      example: "none"
      selector:
        text:
