select_picture_mode:
  name: Select Picture Mode
  description: Send to samsung TV the command to change picture mode.
  fields:
    entity_id:
      name: Entity Name
      description: Name of the target entity
      required: true
      example: "media_player.tv"
      selector:
        entity:
          integration: samsungtv_smart
    picture_mode:
      name: Picture Mode
      description: Name of the picture mode to switch to. Possible options
        can be found in the picture_mode_list state attribute.
      required: true
      example: "Standard"
      selector:
        text:

set_art_mode:
  name: Set Art Mode
  description: Send to samsung TV the command to set art mode.
  fields:
    entity_id:
      name: Entity Name
      description: Name of the target entity
      required: true
      example: "media_player.tv"
      selector:
        entity:
          integration: samsungtv_smart

select_artwork:
  name: Select Artwork
  description: Display a specific artwork on The Frame TV.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of artwork to display (e.g., 'SAM-F0206')
      required: true
      example: "SAM-F0206"
      selector:
        text:
    show:
      name: Show Immediately
      description: Whether to display artwork immediately
      default: true
      selector:
        boolean:

upload_artwork:
  name: Upload Artwork
  description: Upload a custom image to The Frame TV.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    file_path:
      name: File Path
      description: Path to image file (PNG or JPEG)
      required: true
      example: "/config/www/my_art.png"
      selector:
        text:
    file_type:
      name: File Type
      description: Image format
      default: "PNG"
      selector:
        select:
          options:
            - "PNG"
            - "JPEG"
    matte:
      name: Matte Color
      description: Optional matte color (e.g., 'modern_apricot')
      example: "modern_apricot"
      selector:
        text:

delete_artwork:
  name: Delete Artwork
  description: Remove uploaded artwork from The Frame TV.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of uploaded artwork to delete (e.g., 'MY-F0020')
      required: true
      example: "MY-F0020"
      selector:
        text:

set_photo_filter:
  name: Set Photo Filter
  description: Apply a filter effect to artwork.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of artwork to apply filter to
      required: true
      example: "SAM-F0206"
      selector:
        text:
    filter:
      name: Filter Name
      description: Filter effect to apply (e.g., 'ink', 'watercolor')
      required: true
      example: "ink"
      selector:
        text:

set_art_brightness:
  name: Set Art Mode Brightness
  description: Adjust brightness for Art Mode display.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    brightness:
      name: Brightness
      description: Brightness level (0-10 on most TVs)
      required: true
      example: 5
      selector:
        number:
          min: 0
          max: 10
          mode: slider

set_art_color_temperature:
  name: Set Art Mode Color Temperature
  description: Adjust color temperature for Art Mode display.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    temperature:
      name: Color Temperature
      description: Color temperature value (-5 to 5 on most TVs)
      required: true
      example: 0
      selector:
        number:
          min: -5
          max: 5
          mode: slider

change_artwork_matte:
  name: Change Artwork Matte/Frame
  description: Change the matte or frame style for an artwork.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of artwork to change matte for
      required: true
      example: "MY-F0020"
      selector:
        text:
    matte_id:
      name: Matte Style
      description: Matte/frame style (e.g., 'shadowbox_polar', 'modern_apricot', 'none')
      required: false
      example: "shadowbox_polar"
      selector:
        text:
    portrait_matte_id:
      name: Portrait Matte Style
      description: Matte for portrait orientation (optional)
      required: false
      example: "shadowbox_polar"
      selector:
        text:

set_artwork_favorite:
  name: Set Artwork Favorite
  description: Mark an artwork as favorite or remove from favorites.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    artwork_id:
      name: Artwork ID
      description: ID of artwork
      required: true
      example: "MY-F0020"
      selector:
        text:
    favorite:
      name: Favorite Status
      description: Mark as favorite
      default: true
      selector:
        boolean:

set_art_slideshow:
  name: Set Art Slideshow
  description: Configure auto-rotation slideshow for Art Mode.
  target:
    entity:
      integration: samsungtv_smart
      domain: media_player
  fields:
    duration:
      name: Duration
      description: Rotation interval in minutes (0 to disable)
      default: 60
      selector:
        number:
          min: 0
          max: 1440
          unit_of_measurement: "minutes"
    shuffle:
      name: Shuffle
      description: Shuffle artwork order
      default: true
      selector:
        boolean:
    category:
      name: Category
      description: Artwork category (2=My Pictures, 4=Favorites, 8=Store Art)
      default: 2
      selector:
        select:
          options:
            - label: "My Pictures"
              value: "2"
            - label: "Favorites"
              value: "4"
            - label: "Store Art"
              value: "8"
